// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Summarizes daily fleet activities, including notable events, delays, and resource utilization.
 *
 * - summarizeFleetActivity - A function that handles the summarization process.
 * - SummarizeFleetActivityInput - The input type for the summarizeFleetActivity function.
 * - SummarizeFleetActivityOutput - The return type for the summarizeFleetActivity function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeFleetActivityInputSchema = z.object({
  dailyEvents: z
    .string()
    .describe('A detailed report of the day\'s fleet activities, including notable events, delays, and resource utilization.'),
});
export type SummarizeFleetActivityInput = z.infer<typeof SummarizeFleetActivityInputSchema>;

const SummarizeFleetActivityOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the day\'s fleet activities.'),
  recommendations: z
    .string()
    .describe('Recommendations for optimized routes and resource allocations based on the day\'s events.'),
});
export type SummarizeFleetActivityOutput = z.infer<typeof SummarizeFleetActivityOutputSchema>;

export async function summarizeFleetActivity(
  input: SummarizeFleetActivityInput
): Promise<SummarizeFleetActivityOutput> {
  return summarizeFleetActivityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeFleetActivityPrompt',
  input: {schema: SummarizeFleetActivityInputSchema},
  output: {schema: SummarizeFleetActivityOutputSchema},
  prompt: `You are a fleet management expert tasked with summarizing daily fleet activities and providing recommendations for improvement.

  Summarize the following daily fleet activities report and provide actionable recommendations for optimizing routes and resource allocation.

  Daily Fleet Activities Report:
  {{dailyEvents}}`,
});

const summarizeFleetActivityFlow = ai.defineFlow(
  {
    name: 'summarizeFleetActivityFlow',
    inputSchema: SummarizeFleetActivityInputSchema,
    outputSchema: SummarizeFleetActivityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
